enum MenuItemType {
  MAIN_COURSE
  SIDE
}

type MenuItem {
  _id: ID!
  name: String!
  price: Float!
  image: String
  type: MenuItemType!
}

input NewMenuItemInput {
  name: String!
  price: Float!
  image: String
  type: MenuItemType!
}

input UpdateMenuItemInput {
  name: String
  price: Float
  image: String
}

type S3Object {
  ETag: String
  Location: String!
  Key: String!
  Bucket: String!
}

type Query {
  menuItems: [MenuItem]!
  menuItem(id: ID!): MenuItem!
}

type Mutation {
  newMenuItem(input: NewMenuItemInput!): MenuItem!
  uploadImage(file: Upload!): S3Object
  updateMenuItem(id: ID!, input: UpdateMenuItemInput!): MenuItem!
  removeMenuItem(id: ID!): MenuItem!
}
